### PR TITLE
dockerd: new setting log-max-line

### PR DESCRIPTION
**Pull request by giuseppe**
allow to set the maximum log line to read.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1427308

### CODE REVIEW

**Comment by portante** [comment]
Have you read through the comments in https://github.com/moby/moby/issues/32923?

**Comment by giuseppe** [comment]
My understanding was that we still want this to be configurable, or what am I missing here?

**Comment by alexandruionica** [comment]
This would be a huge feature for us. 

We have the same problem with larger than 16KB log lines and we'd be willing to spend the extra memory with Docker by increasing the logging max size.

Our approach would be to say that what we choose at the upper bound in docker is the max size and that we won't assemble larger records but unfortunately, 16KB is just too low nowadays.

Re-assembling log lines down the track in processing software is way more complicated and resource intensive than expected. For example if Docker is set to use the Journald logging driver and then Fluentd is set to read from Journald , the reasonable expectation would be to expect re-assembly to whatever size is desired to happen in Fluentd. Unfortunately in practice such an approach is troublesome because the Fluentd thread processing the log lines will have to block (with a timeout) before all the parts of a log line are made available which most likely will trash performance.
Trying to assemble the log line on the remote end where all log lines are aggregated and stored is even worse from a performance point of view.

Since ~10 months ago Journald also switched to allowing a configurable max line size (defaults to 48KB).

So it would be great if this patch would be accepted.

**Comment by giuseppe** [comment]
is this patch still useful/needed?  Should I close the PR?

**Comment by alexandruionica** [comment]
Still needed but unless there is a chance it is accepted then close it.

**Comment by giuseppe** [comment]
given there is no interest in this PR I am going to close it

**Comment by dcaldwel** [comment]
As @alexandruionica commented, yes, it is still needed.

**Comment by therevoman** [comment]
Large Customer just asked for this feature.

**Pull request closed without merging**
