### PR TITLE
Fixes for reading from the journald log driver

### PR DESCRIPTION
**Pull request by nalind**
This is the set of fixes being proposed for https://bugzilla.redhat.com/show_bug.cgi?id=1314463, which fix a couple of race conditions and improve error reporting when we're reading from the journald log driver.

### CODE REVIEW

**Comment by lsm5** [comment]
@nalind @runcom @rhatdan wondering if we could revert this merge for now. Waiting to have a new build once we have @mrunalp's cgroups fix merged in here.

**Comment by runcom** [comment]
@lsm5 can you build from previous commit hash instead of reverting here?

**Comment by lsm5** [comment]
@runcom but iinm, mrunal would be having a new fix coming in...correct me if i'm wrong

**Comment by lsm5** [comment]
but let's wait for @mrunalp.

**Comment by mrunalp** [comment]
I have one fix for additional debugs. I will create a PR shortly.

**Comment by rhatdan** [comment]
Mrunal I don't believe we are getting any fixes into RHEL unless they are true blockers.

**Comment by mrunalp** [comment]
@rhatdan ack, the debug PR isn't super urgent.

**Comment by rhatdan** [comment]
Lets get them into docker-1.10 and Master.  But lets forget about docker-1.9 updates going forward.

**Comment by mrunalp** [comment]
Okay sure

**Pull request merged**
