### PR TITLE
import/export our patches

### PR DESCRIPTION
**Pull request by runcom**
You all might dislike this so feel free to just close it :)

This patch basically saves our currently applied patches under `patches/` (much like distributions packagers do with src package with applied patches)

You'll find a script `patches/export_patches.sh` which basically helps you exporting patches from `HEAD` (there's a short usage in the script also)
I did this so we have all patches around and when rebasing fedora-1.* branches we won't forget any patch.
So everytime we apply a patch we could export it (`./patches/export_patches.sh 1`) and save it in the repo. Everytime we need to save all applied patches to rebase the branch, we first export them, rebase and reapply them (taking care of conflicts), and then reexport them (to have the latest applied ones)

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
Given the frequent rebasing, I think this is a good idea.  One alternative would be to just drop the `projectatomic/docker` fork, and keep these patches in Fedora dist-git.

**Comment by runcom** [comment]
> Given the frequent rebasing

this was the primary reason, avoiding losing patches :(

**Comment by runcom** [comment]
@rhatdan I've update the PR to just save the patches under `patch/` from `git format-patch`

It contains my "show registry patch" as well

**Comment by rhatdan** [comment]
This patch no longer includes your script?

Currently this is what I do everyday.

I login to machine into docker directory and do 

1. git pull origin master

Then no matter what I do 

2. git commit -a

Then I do

3. git rebase -i origin

Now I save that and wait for something to fail.

4. On each failure, I attempt to cleanup the code and run a compile test on it.

Once I have it recompiling, I do

```
5. git commit -a
6. git rebase --continue
```
If something fails again I go to Step 4.

If something fails so bad that it will be a massive change to the patch, I sometimes pull the patches and send them to the original patch creator and ask them to rebase.  (This is where we sometimes loose a patch).  Only one I do this to regularly is the Registry Patches, Michal Minimar.

How would you want the new behaviour to be on a daily basis?

Should I run your script, which would extract all of the existing patches.  And save them?  Should this save them in a different git repo?  Should it create a new set of patches for each day?  I think pull and reapplying the patches would be more time consuming then what I currently need to do.

**Comment by runcom** [comment]
> If something fails so bad that it will be a massive change to the patch, I sometimes pull the patches and send them to the original patch creator and ask them to rebase. (This is where we sometimes loose a patch). Only one I do this to regularly is the Registry Patches, Michal Minimar.
> 
> How would you want the new behaviour to be on a daily basis?
> 
> Should I run your script, which would extract all of the existing patches. And save them? Should this save them in a different git repo? Should it create a new set of patches for each day? I think pull and reapplying the patches would be more time consuming then what I currently need to do.

Accidentally losing patches was one of the main reason to save patches in the repo (show registries patch is also getting lost sometimes)

I think the script isn't needed at all with `git format-patch`.

I would just `git format-patch` once, save the patches in the repo and have them recreated every time a rebase is finished (so patches saved are always clean and latest) and we shouldn't lose/forgot any.

**Comment by rhatdan** [comment]
So you want 

git rm -f patches/*patch
git format-patch -o patches
git add patches/*.patch
git pull origin master
git commit -a
git rebase -i origin
CLEANUP
git rebase --continue
FAIL goto CLEANUP
Success.

Then make sure I have all of the patches in /patches still applied?

**Comment by runcom** [comment]
Yup! As soon as we always have all the patches saved every methods to export them and being able to track them is fine (as @cgwalters said we can have host the patch elsewhere but I think here in the repo is fine)

**Comment by runcom** [comment]
I've seen it's included on our branches, closing

**Pull request closed without merging**
