### PR TITLE
BACKPORT: Add additional debug information to cgroup writes

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom @rhatdan PTAL

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
:+1:

**Comment by runcom** [comment]
@mrunalp @rhatdan shall we get this in if we're going to have another docker 1.9 release in RHEL?

**Comment by mrunalp** [comment]
Yeah, it will be good to have.

**Comment by runcom** [comment]
I think this won't hurt and will be helpful in case we'll ship a docker 1.9 in RHEL so merging

**Comment by rhatdan** [comment]
Make sure if we build a new docker-1.9 in RHEL we do  it with golang < 1.6 or we  add the /run/docker.sock patch.  I am pretty sure kubernetes might be looking to build with golang 1.6 soon.

**Comment by runcom** [comment]
ack - I think RHEL won't have go1.6 for some time so docker-1.9 will be built with go < 1.6 hopefully

**Pull request merged**
