### PR TITLE
Fix building secrets patch on Windows

### PR DESCRIPTION
**Pull request by nalind**
Fix the "cross" target by correcting a type mismatch on Windows in the "secrets" patch.  Needs PR#46 to also get static builds to work on Linux.

### CODE REVIEW

**Comment by runcom** [comment]
@rhatdan @nalind from the code seems like `fedora-1.10` and `rhel7-1.10` branches are already fixed, I'll run `make cross` and see what happens.
@rhatdan did you already fix this on those branches?

**Comment by runcom** [comment]
yup, we can close this, branches are working correctly with `make cross`

**Comment by nalind** [comment]
Okay then.

**Comment by rhatdan** [comment]
@nalind Why did you reopen?

**Comment by runcom** [comment]
@rhatdan because w/o this docker on windows errors out when in `setupMounts` https://github.com/projectatomic/docker/blob/fedora-1.10/daemon/volumes_windows.go#L30 because the `Source` in mount we're returning is empty

**Comment by nalind** [comment]
@rhatdan I'd closed it after the alternate change to fix "make cross" was added, but the conversation we had with @runcom at https://github.com/nalind/docker/commit/5d1d3e8495e95c7618cfb5986839863d021b90da#commitcomment-15557498 indicated that "make cross" succeeding isn't enough, so I reopened it.

**Comment by rhatdan** [comment]
@runcom So you think this patch is the only way to fix?  I wish we could get it so SecretMount was only used in Linux version.

**Comment by runcom** [comment]
> @runcom So you think this patch is the only way to fix? I wish we could get it so SecretMount was only used in Linux version.

it's only for linux right now, but we need to differentiate the functions in linux/windows and this seems the only way to not append an empty mount which could "potentially" be used on windows

AGAIN: `make cross` is working fine and since we ship our docker only on rhel/linux this patch seems unnecessary but I think it's better to include it

**Comment by rhatdan** [comment]
Merged.

**Comment by runcom** [comment]
@rhatdan  btw, I've reworked the patch a bit -> https://github.com/runcom/docker/commit/d1d24ca672e98ebd833126bca39999a5cb72bf23

and it's on a clean rhel7-1.10 branch rebased on top of docker-1.10 release branch (I've sent you an email about this also)

**Comment by rhatdan** [comment]
I think I merged your fixes correctly.  Take a look at https://github.com/projectatomic/docker/tree/secrets

**Comment by runcom** [comment]
@rhatdan please take a look at my other PR

I've cleaned everything and the PR has tons of fixes

**Comment by runcom** [comment]
The fixes you took are outdated cause today I fixed a bug in the secrets path :)

**Pull request closed without merging**
