### PR TITLE
Dockerfile: don't build for Windows

### PR DESCRIPTION
**Pull request by jlebon**
Some of our patches don't play nice with the Windows build. This causes
"make test" to fail on the cross target. Let's not even bother trying to
build for Windows for now.

### CODE REVIEW

**Comment by jlebon** [comment]
The specific error is:

```
Building: bundles/1.9.0-rc4/cross/windows/amd64/docker-1.9.0-rc4.exe
# github.com/docker/docker/api/server/router/local
api/server/router/local/container.go:190: undefined: devmapper.WarnOnLoopback
api/server/router/local/container.go:190: undefined: devmapper.LoopbackInUse
Makefile:67: recipe for target 'test' failed
make: *** [test] Error 1
```

which is due to the devmapper warning msg patch (the devmapper driver is not built on Windows, but `container.go` is).

**Comment by rhatdan** [comment]
Shouldn't we just fix the patch to only do this devmapper.WarnOnLoopback on windows?

@rhvgoyal

**Comment by rhvgoyal** [comment]
@rhatdan 

Even if we check for windows at run time, it will not help us with compile time failure. I think we should provide dummy definitions of devmapper.WarnOnLoopback for windows.

@shishir-a412ed can you please take a look at this one.

**Comment by rhatdan** [comment]
Exactly.  This would solve the problem without having to disable windows builds.

**Comment by shishir-a412ed** [comment]
@rhatdan 
I have the fix for this, however I am not able to fork 'projectatomic/docker'.
As my github account already has a fork of 'docker/docker'.

Should I e-mail you the patch ? It's just a file you need to place in 'daemon/graphdriver/devmapper' directory.

**Comment by jlebon** [comment]
@shishir-a412ed You should be able to manually select your `docker/docker` fork and specific branch when comparing before doing a PR: https://github.com/projectatomic/docker/compare (set base fork to `projectatomic/docker` and head fork to `shishir-a412ed/docker`).

**Comment by shishir-a412ed** [comment]
@jlebon 
Mine is showing `shishir-a412ed/docker` in base fork, and `projectatomic/docker` in head fork. Another problem is `shishir-a412ed/docker` is completely rebased with `upstream (docker/docker)`, however `projectatomic/fedora-1.9` is not. So when I create a PR it has like 100+ files which are not part of my patch.

**Comment by jlebon** [comment]
@shishir-a412ed 

Right, so first you have to fetch from `projectatomic`, then work on top of the `fedora-1.9` branch, then create a new branch on your fork so that you can make the PR:

```
$ git remote add atomic https://github.com/projectatomic/docker
$ git fetch atomic
$ git checkout fedora-1.9 -b my-bug-fix
$ <work and commit stuff>
$ git push origin my-bug-fix # replace origin here by whatever you named your personal remote (if you do a `git remote -v`, it's the one that has a push url for `shishir-a412ed/docker`)
```

Then in the compare view, select `projectatomic/docker` for base fork, and branch `fedora-1.9` and then `shishir-a412ed/docker` for head fork and branch `my-bug-fix`.

Hope this helps!

**Comment by shishir-a412ed** [comment]
@jlebon 
executing: `git checkout fedora-1.9 -b my-bug-fix` gives me this:

`fatal: Cannot update paths and switch to branch 'my-bug-fix' at the same time.
Did you intend to checkout 'fedora-1.9' which can not be resolved as commit?`

**Comment by shishir-a412ed** [comment]
@rhatdan @rhvgoyal @jlebon 
https://github.com/projectatomic/docker/pull/18

**Comment by jlebon** [comment]
Closing this since @shishir-a412ed fixed it.

**Pull request closed without merging**
