### PR TITLE
Stabilize 1.10.3 [rhel7-1.10.3]

### PR DESCRIPTION
**Pull request by runcom**
Selection of commits from docker/docker which aim at fixing some nasty bugs.

ping @mrunalp @rhatdan @timothysc PTAL - I'd love if we could run k8s tests as we're doing for https://bugzilla.redhat.com/show_bug.cgi?id=1341906 to test this out.

The full docker test suite is running fine with these commits applied.

I'll port this PR to fedora-1.10.3 as well.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by timothysc** [comment]
thx @runcom 

/cc @mffiedler @jeremyeder - we should enqueue another test-run once all is said and done.

**Comment by jeremyeder** [comment]
Great progress report from OpenShift QE this morning along these lines, Tim! :-)

**Comment by mrunalp** [comment]
LGTM

**Comment by runcom** [comment]
@mrunalp

I believe first batch of tests (or half of them) ran just fine (fine as in no deadlock) with the previous patch /cc @stevekuznetsov 

Lokesh is going to build a new docker with this patch applied to be tested one more time

**Pull request merged**
