### PR TITLE
Fix cross compile rhel

### PR DESCRIPTION
**Pull request by runcom**
Fix CI in rhel7-1.11 branch (due to cross compile bug in audit), I'll fix the patch into 1.12 branches

@mrunalp @rhatdan PTAL and merge if CI is green

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
Let's wait for CI to be green and then I'll merge

**Comment by runcom** [comment]
Seems like there are other cross compile fix to be made, will work on it asap

**Comment by runcom** [comment]
```
# github.com/docker/docker/docker
/usr/local/go/pkg/tool/linux_amd64/link: running x86_64-w64-mingw32-gcc failed: exit status 1
/usr/lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lpthread
collect2: error: ld returned 1 exit status
```
Has anyone any idea about why this is happening? I'm in the middle of nowhere right now and win cross compilation isn't working :confused: @rhatdan @mrunalp @nalind

**Comment by rhatdan** [comment]
No idea,  Looks like something for linux is being compiled on Windows?

**Comment by runcom** [comment]
Yes, it's definitely something in gcc mingw which is (I think) used by the go toolchain to cross compile - but yet no idea about mingw - I'd  say I can completely disable windows compilation cause our binaries aren't used in windows enviroment - but just testing...

**Comment by rhatdan** [comment]
Hopefully @nalinp will have an idea.

**Comment by nalind** [comment]
I'm still running through it on my laptop, but does adding mingw64-winpthreads (or mingw64-winpthreads-static) to the list of dependencies in distros/Fedora.json might do it.

**Comment by runcom** [comment]
awesome, I've noticed mingw64-winpthreads in dnf search but wasn't sure it was really related, I'll try it now

**Comment by runcom** [comment]
The only difference between those 1.11, 1.12 branches and the previous working 1.10.3 is that Golang is 1.5.4 (as opposed to 1.5.3 in 1.10.3)

**Comment by runcom** [comment]
`mingw64-winpthreads` it isn't working.. I'll test with `mingw64-winpthreads-static` now

**Comment by runcom** [comment]
@nalind using `-static` did the trick and cross compilation works correctly, thanks

**Comment by runcom** [comment]
green again here as well :)

**Pull request merged**
