### PR TITLE
build with debug info

### PR DESCRIPTION
**Pull request by lsm5**
From: Jan Chaloupka <jchaloup@redhat.com>
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

See: http://pkgs.fedoraproject.org/cgit/rpms/docker.git/commit/build-with-debug-info.patch?id=b030bbd29362fe434266c1d4b79ab72874ecd45d

### CODE REVIEW

**Comment by lsm5** [comment]
we're carrying this patch in our rpm dist-git for now

**Comment by lsm5** [comment]
@rhatdan @ingvagabund ping

**Comment by runcom** [comment]
@lsm5 is this just for docker-1.10?

**Comment by lsm5** [comment]
hmm, I see it's only on our rawhide branch as yet, gotta check if other branches could use it too.

**Comment by ingvagabund** [comment]
First, it needs to be tested if the docker daemon runs properly. The last time it did not start at all. Currently, the daemon starts. Do you have integration tests you can run on pure docker?

**Comment by rhatdan** [comment]
@lsm5 What is the state of this at this time.

**Pull request closed without merging**
