### PR TITLE
api: client: info: print a warning if dm is using a loopback file

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@rhatdan this can wait till docker/docker decides if the same patch could be merged there

**Comment by rhatdan** [comment]
I will take it now, and remove the other patch.  I like this a lot more.

**Comment by runcom** [comment]
fair enough, in case it will be merged upstream we can just remove it from our branch

**Comment by rhatdan** [comment]
That's the plan and hope.

**Comment by runcom** [comment]
@rhatdan closing this now that this warning went upstream! Yaii!

**Comment by rhatdan** [comment]
Awesome you must have the magic touch upstream

**Pull request closed without merging**
