### PR TITLE
container: memory_store: fix deadlock [rhel7-1.10.3]

### PR DESCRIPTION
**Pull request by runcom**
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1341906

@rhatdan @mrunalp PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by mrunalp** [comment]
Did we hear back from testing on openshift?

**Comment by runcom** [comment]
@mrunalp not yet, testing

**Comment by mrunalp** [comment]
LGTM. Not sure if we want to wait for testing results. Irrespective, the change makes sense as we don't need full locks for just read access.

**Comment by runcom** [comment]
@mrunalp

I believe first batch of tests (or half of them) ran just fine (fine as in no deadlock) with the previous patch /cc @stevekuznetsov 

Lokesh is going to build a new docker with this patch applied to be tested one more time

**Comment by stevekuznetsov** [comment]
4/100 extended test runs for Origin failed in the conformance suite, none of which exhibited the Docker daemon deadlock. Running another batch as ~40 test runs flakes in the setup steps

**Comment by rhatdan** [comment]
@rh-atomic-bot r+

**Comment by stevekuznetsov** [comment]
On the second set of tests @runcom's first set of patches did not help, found one instance with the Docker daemon hang.

**Comment by runcom** [comment]
let's try with this patch - as I'm sure there's another deadlock in image deletion and this patch should address it

**Pull request merged**
