### PR TITLE
secrets

### PR DESCRIPTION
**Pull request by rhatdan**
Currently we are mounting over /run/secrets if the user mounted something there.  This patch causes the secrets patch to be mounted before any volume mounts are mounted, also makes /run/secrets read/writable.

Signed-off-by: Dan Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@runcom PTAL.

This should fix https://github.com/openshift/origin/issues/6981

**Comment by rhatdan** [comment]
The pull request is wrong since it is fedora against rhel, but it still works.  Just want to make sure I did not do anything stupid.

**Comment by runcom** [comment]
If we mount this before anything else, then we mount something over it, does this overwrite everything in /run/secrets or just merge the contents of the two? 

BTW, I'll take care of applying this correctly to rhel and Fedora branches

**Comment by rhatdan** [comment]
If someone mounted on /run/secrets then we loose.  If they mount on a subdir like k8s is doing, they will merge.

I tested this by doing the following command.

docker run -ti -v /etc:/run/secrets/etc --rm fedora sh

**Comment by runcom** [comment]
alright, I'll fix our rhel super secret patches in both *-1.10 branches and  *-1.11

**Comment by rhatdan** [comment]
Should go in Fedora also.

**Comment by runcom** [comment]
sure, I've pushed fedora and rhel 1.10, closing this, I'll fix *-1.11 branches (both rhel and fedora)

I'll run all integration tests after I fix 1.11 branches and hopefully @lsm5 can build rc3 as soon as he comes online

**Comment by mrunalp** [comment]
The fix LGTM.

**Pull request closed without merging**
