### PR TITLE
Backport always store image digest when pulling and pushing

### PR DESCRIPTION
**Pull request by runcom**
@jwhonce @ncdc @rhatdan 

Discussed yesterday, I went ahead and backported those patches - integration tests run just fine (ran locally). Let me know if fedora-1.10.3 needs this as well.

### CODE REVIEW

**Comment by rhatdan** [comment]
We could maybe ship these for Fedora, but I am hoping we are done with docker-1.10 for RHEL, after rhel7.3.

**Comment by ncdc** [comment]
We need fedora to be in lock step with rhel

**Comment by ncdc** [comment]
Or newer

**Comment by rhatdan** [comment]
Well Fedora would be newer then RHEL in that case.  But the question is
what version of docker is the default in rhel7.3.1?

**Comment by ncdc** [comment]
cc @smarterclayton @derekwaynecarr @directxman12

**Comment by ncdc** [comment]
@rhatdan are you asking if it should be 1.10 vs 1.12?

**Comment by runcom** [comment]
> @rhatdan are you asking if it should be 1.10 vs 1.12?

1.12 already has this

**Comment by rhatdan** [comment]
@ncdc I am just pointing out that we might not update docker-1.10 for RHEL.  We can add this to Fedora.

**Comment by ncdc** [comment]
Makes sense. Thanks for the clarification.

**Comment by runcom** [comment]
@rhatdan @ncdc is it OK if I apply these patches to the Fedora branch and rebuild 1.10.3 for F23 and F24?

**Comment by ncdc** [comment]
SGTM

**Comment by rhatdan** [comment]
Yes

**Comment by runcom** [comment]
Closing this now, I'll cherry pick these patches in fedora-1.10.3 and rebuild docker in F23 and F24 tomorrow morning. Thanks.

**Comment by runcom** [comment]
@rhatdan just to be sure - was there a consesus to update this one in RHEL?

**Comment by rhatdan** [comment]
I thought there was.

**Comment by runcom** [comment]
@rhatdan I re-opened this since I heard some discussion about this on IRC - not sure it was going to be merged - anyway, let's just make sure we don't rebuild for RHEL at this point

**Comment by rhatdan** [comment]
Ok

**Comment by runcom** [comment]
> Ok

I'm gonna remove these patches from the rhel7-1.10.3 branch until we have consensus to merge them (/cc @ncdc @derekwaynecarr)

**Comment by runcom** [comment]
Reverted these commits from rhel7-1.10.3 - if we'll ever need them there's a branch https://github.com/projectatomic/docker/commits/rhel7-1.10.3-with-192 which has them and I can easily reintegrate them

**Comment by derekwaynecarr** [comment]
we need these patches to support ose 3.3.1

**Comment by runcom** [comment]
These patches are breaking something in openshift in Fedora (these patches are in the Fedora docker) https://bugzilla.redhat.com/show_bug.cgi?id=1380474. We need to clear out that bz before getting this into rhel, when is 3.3.1 going out? /cc @rhatdan

**Pull request merged**
