### PR TITLE
Setup hooks independenly of network namespace

### PR DESCRIPTION
**Pull request by mrunalp**
This ensures that the hooks are always called whether one uses
--net=host, --net=container:<id> or container private network namespace.

@rhatdan @runcom PTAL

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM but from a recent conversation with @rhatdan on another PR I'm not sure we're going to ship 1.10.3 in rhel again - we may probably need this for Fedora instead (is 1.12 needing this also?)

**Comment by mrunalp** [comment]
@runcom I think we will need to support this in docker 1.10.3 for OpenShift/kubernetes as this breaks starting systemd in pods. See https://bugzilla.redhat.com/show_bug.cgi?id=1364237
We can port this to other branches as well.

**Comment by runcom** [comment]
Cool, I'll take care of cherry picking to fedora-1.10.3. 

Ping @rhatdan to merge

**Comment by mrunalp** [comment]
@runcom Yeah, thanks. @rhatdan would know for sure whether this needs to be merged for docker 1.10 or not.

**Comment by rhatdan** [comment]
We have to open this up for conversation with Martin Jenner and David Darrah, to see what they think.

**Comment by runcom** [comment]
@rhatdan I'll cherry-pick this into Fedora

**Comment by runcom** [comment]
cherry-picked into fedora-1.10.3 - @mrunalp does this need to be cherry picked in docker-1.12 as well? or is it fixed there?

**Comment by mrunalp** [comment]
I will look into that and open a PR if any changes are necessary. It wont be a straight cherry pick.

**Comment by mrunalp** [comment]
From a quick look at the code in docker 1.12, we shouldn't need this fix over there.

**Pull request merged**
