### PR TITLE
BACKPORT: Fixes for --cgroup-parent slices to expand correctly

### PR DESCRIPTION
**Pull request by mrunalp**
This fix was missing in docker-latest package.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@rhatdan @runcom PTAL
cc: @lsm5 @edsantiago

**Comment by runcom** [comment]
@mrunalp does this need to be put in the Fedora 1.10.3 branch? Would be good to add a note in the Readme to mention this patch also (since we're trying to keep the Readme in sync with all our carryings)

**Comment by runcom** [comment]
LGTM, waiting on CI to merge

**Comment by mrunalp** [comment]
@runcom Yeah, we need this in Fedora as well. I will update the Readme.

**Comment by mrunalp** [comment]
@runcom README.md has this listed
```
BACKPORT:-Ensure-that-we-join-all-the-cgroups.patch

https://github.com/opencontainers/runc/pull/491
```

Not sure how it disappeared from the tree. Or maybe just README got copied without the actual patch.

**Comment by mrunalp** [comment]
@runcom NVM that is a different patch. I will update the README with another comment.

**Comment by mrunalp** [comment]
Updated README

**Pull request merged**
