### PR TITLE
BACKPORT: Overlay2 quota support

### PR DESCRIPTION
**Pull request by rhvgoyal**
Backport overlay2 quota support for docker-1.13.1. Most of the bits are already there. Just had to introduce another patch to support passing option to daemon so that a common size default is applied to all containers.

### CODE REVIEW

**Comment by rhvgoyal** [comment]
@rhatdan @runcom PTAL

**Comment by rhvgoyal** [comment]
cc @mbarnes

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@runcom @lsm5 lets get new packages built for RHEL so that OpenShift Online can start experimenting with the quota changes.

**Comment by lsm5** [comment]
On Wed, Sep 20, 2017 at 01:31:28PM +0000, Daniel J Walsh wrote:
> @runcom @lsm5 lets get new packages built for RHEL so that OpenShift Online can start experimenting with the quota changes.

will do..

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/projectatomic/docker/pull/274#issuecomment-330852100

-- 
Lokesh
Freenode, OFTC: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Pull request merged**
