### PR TITLE
Allow to skip manifest schema V2 push [fedora-1.10.3]

### PR DESCRIPTION
**Pull request by runcom**
same as #169 but for fedora

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM but Yuck.  How long will we need to carry this. also good we are not document it, so customers don't know about it.

**Comment by runcom** [comment]
@rhatdan indeed that flag is hidden - my best guess is that we'll carry this just 1.10.3 for ppl migrating from 1.9 /cc @miminar @smarterclayton

**Comment by miminar** [comment]
@runcom I wouldn't count on it. We will need to be able to push both v1 and v2 manifests to v2 registries from our infrastructure for extended period of time - until our customers migrate to docker 1.10+ or we drop support, which can take years.

If we don't want to carry it, we'll need to force our infrastructure team to use different versions of docker for pushes to docker hub.

**Comment by runcom** [comment]
> @runcom I wouldn't count on it. We will need to be able to push both v1 and v2 manifests to v2 registries from our infrastructure for extended period of time - until our customers migrate to docker 1.10+ or we drop support, which can take years.
> 
> If we don't want to carry it, we'll need to force our infrastructure team to use different versions of docker for pushes to docker hub.

alright - that way - my opinion is tto not carry this patch since this patch won't be accepted upstream in any way.



> If we don't want to carry it, we'll need to force our infrastructure team to use different versions of docker for pushes to docker hub.

could you evaluate this? this patch isn't that big but you might want to pursue this way

**Comment by smarterclayton** [comment]
We'll probably need this until we can drop support for Docker 1.9 and OpenShift 3.1 for RHEL customers - I don't know what the window is for that?

**Comment by smarterclayton** [comment]
This is pretty important to us - if we need to discuss more let's try to do that in the next day or so.

**Pull request merged**
