### PR TITLE
info: show registries

### PR DESCRIPTION
**Pull request by runcom**
Code from https://github.com/projectatomic/docker/pull/20 isn't in fedora-1.10 (nor in any other RH branch) anymore, adapted and readded it, @rhatdan do you know what's happened? seems weird

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
bot, add author to whitelist

**Comment by cgwalters** [comment]
This PR looks wrong, there are a lot of other commits besides the one from #20 , right?

**Comment by runcom** [comment]
this is against fedora-1.10 branch and probably @rhatdan  just updated the patches there and commits changed

**Comment by rhatdan** [comment]
Merged

**Comment by runcom** [comment]
thx

**Pull request closed without merging**
