### PR TITLE
Prevent unnecessary blob uploads (docker-1.12.2)

### PR DESCRIPTION
**Pull request by miminar**
Backporting upstream docker/docker#26564

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1372065

### CODE REVIEW

**Comment by runcom** [comment]
@miminar something is wrong with the rebase of those patches. I pushed 1.12.2 this morning so you probably had an out of sync branch now.

**Comment by miminar** [comment]
@runcom Ouch. Updated.

**Comment by runcom** [comment]
lgtm

**Comment by runcom** [comment]
I'll cherry-pick those patches to docker-1.12 branch since this is just a backport

**Comment by miminar** [comment]
Thanks!

**Pull request merged**
