### PR TITLE
Set PkgVersion at rpmbuild time.  Default: "<unknown>"

### PR DESCRIPTION
**Pull request by jwhonce**
Set PkgVersion at rpmbuild time vs. runtime using sed in the docker.spec file.  This was done to remove the dependency on running rpm every time docker version/info is called.

Default: `<unknown>` when the executable is built not using rpmbuild.

The docker version command shows the package versions compiled into the source.

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

```
9:58:17 [github.com/docker/docker] ‹pr/projectatomic/232*› docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: <unknown>
 Go version:      go1.7.5
 Git commit:      87964a1
 Built:           Thu Mar 23 09:57:02 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: <unknown>
 Go version:      go1.7.5
 Git commit:      87964a1
 Built:           Thu Mar 23 09:57:02 2017
 OS/Arch:         linux/amd64
```

**Comment by runcom** [comment]
@jwhonce I'll port this PR to 1.13.1 and 17.03.1-ce

**Comment by runcom** [comment]
all done for other branches, thanks @jwhonce

**Comment by rhatdan** [comment]
Can we merge this and the previous rpm patches together in the 1.13 branch.

**Comment by rhatdan** [comment]
We need fixed in the spec files to sed 's/<unknown>/$VERSION/g'

**Comment by runcom** [comment]
@rhatdan I've already ported this fix to 1.13.1 - Lokesh said he already applied the spec changes required also afaict

**Comment by rhatdan** [comment]
Ok, @lsm5 has made the changes and docker version returns the correct data, I am fine with it.
I just want the two patches merged to shrink the number of patches.

**Comment by lsm5** [comment]
I added the change to rhel yesterday, testing and adding to fedora right now.

**Pull request merged**
