### PR TITLE
redhat-ci: build and test in a fedora container

### PR DESCRIPTION
**Pull request by jlebon**
The upstream tests are being run on Debian rather than distro-specific
containers because there is no golang compiler on AH to compile
`gen_dockerfile.go`. We should consider porting it to e.g. python in the
future, but for now, let's just get this in.

### CODE REVIEW

**Comment by jlebon** [comment]
@runcom Once we confirm the PR tester uses the right distro, can you squash with the other redhat-ci commit and propagate to the other branches?

**Comment by cgwalters** [comment]
Why wouldn't we take the "use a build container, install to host" approach here too?

**Comment by jlebon** [comment]
We're just invoking the upstream tests here. It builds a docker container that has all the buildreqs and builds & tests inside. Or do you mean use a container to run `gen_dockerfile.go`? We can do that.

**Comment by cgwalters** [comment]
Oh weird....I didn't realize, this isn't actually *building* this version of docker, it's just testing the host's docker?  This code is weird.

But yeah, we could change this to pull down a `fedora` docker container and install golang inside that.  Or use the upstream golang container.

**Comment by jlebon** [comment]
AFAIU, it does build (and test) this version of docker, just that it does it inside of a docker container.

**Comment by cgwalters** [comment]
I started on https://github.com/projectatomic/docker/pull/226

**Comment by runcom** [comment]
@jlebon is this ready to go? I'll port this commit in other branches

**Comment by jlebon** [comment]
@runcom Yup, let's do it! It still fails, but at least it's building on Fedora now.

**Comment by runcom** [comment]
@jlebon ack, added this commit to other branches. Thanks!

**Pull request closed without merging**
