### PR TITLE
fix retrieving stats when networking is disabled

### PR DESCRIPTION
**Pull request by TomasTomecek**
https://bugzilla.redhat.com/show_bug.cgi?id=1374265

resolves rhbz#1374265
resolves https://github.com/docker/docker-py/issues/1195

### CODE REVIEW

**Comment by runcom** [comment]
> https://bugzilla.redhat.com/show_bug.cgi?id=1374265
> 
> resolves rhbz#1374265
> resolves docker/docker-py#1195

@TomasTomecek is this present only in our docker or does upstream have the same issue?

**Comment by TomasTomecek** [comment]
@runcom I think upstream has the same issue since there were reports in the docker-py bug targeting ubuntu and I also reproduced it on 1.12.1 from fedora rawhide; sorry about the conflict (forgot to update), will push update right away

**Comment by runcom** [comment]
> @runcom I think upstream has the same issue since there were reports in the docker-py bug targeting ubuntu and I also reproduced it on 1.12.1 from fedora rawhide; sorry about the conflict (forgot to update), will push update right away

that's kind of great, but I would rather wait to have the PR accepted and merged upstream before including this here. Could you open a PR upstream to discuss this fix?

**Comment by TomasTomecek** [comment]
Yup, definitely, working on it right now.

**Comment by runcom** [comment]
LGTM

@rhatdan would you merge this in RHEL or just fedora? (I'm cherry-picking in fedora-1.10.3)

**Comment by rhatdan** [comment]
Is this important to RHEL or just something we want fixes in the long run in Fedora?  Are customers seeing this issue? OpenShift?

**Comment by TomasTomecek** [comment]
It was reported via bugzilla by @twiest from OpenShift, so he should prioritize.

**Comment by twiest** [comment]
@rhatdan This is important for RHEL as the OpenShift OPS team uses `docker stats` to look at container usage quite frequently and without this fix, `docker stats` in 1.10 is very unreliable (often showing all 0s).

We also use this same function in our monitoring scripts with docker-py, which are now broken because of this bug.

So I'd prefer it to be a high priority fix if possible.

**Pull request merged**
