### PR TITLE
Remove Overlay2 version check

### PR DESCRIPTION
**Pull request by rhvgoyal**
Right now overlay2 driver checks if kernel version is greater than
4.0.0. But this fails on kernels like rhel and centos kernel version
is old (3.10) but overlay has been backported with multiple lower
layer support. So get rid of this check to make sure overlay2 can
be used on these kernels.

Signed-off-by: Vivek Goyal <vgoyal@redhat.com>

### CODE REVIEW

**Comment by rhvgoyal** [comment]
@rhatdan PTAL.

**Comment by mrunalp** [comment]
:+1:

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
did anyone report this upstream also?
Or is this something we need to carry in docker-1.13 branch also?

**Comment by runcom** [comment]
@rhvgoyal @mrunalp @rhatdan ^^^

**Comment by rhatdan** [comment]
@rhvgoyal Please submit this upstream

**Comment by rhvgoyal** [comment]
@runcom we need to carry this for 1.13. Upstream does not have a better solution than kernel version check yet.

**Comment by runcom** [comment]
@rhvgoyal ack, we need this in newer branches as well then

**Pull request merged**
