### PR TITLE
Fixes for reading from the journald log driver

### PR DESCRIPTION
**Pull request by nalind**
This is the set of fixes being proposed for https://bugzilla.redhat.com/show_bug.cgi?id=1314463, which fix a couple of race conditions and improve error reporting when we're reading from the journald log driver.

### CODE REVIEW

**Comment by runcom** [comment]
@nalind does this needs to be applied on 1.9 also?

**Comment by nalind** [comment]
Yes, and they should cherry pick cleanly.  These are filed as two PRs for upstream, so I'm doing a quick smoke test, to make sure that I didn't miss anything when merging them for this one, before I open a PR against the fedora-1.9 branch.

**Comment by runcom** [comment]
@nalind this also needs a PR against fedora-1.10.3

**Comment by nalind** [comment]
Okay, opened #85.

**Pull request merged**
