### PR TITLE
WIP - Fix for docker ps hang after docker restart with liverestore

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

**- What I did**
Changed the handling of FIFO's when --live-restore is in play.  Without this change the FIFO's were not cleared on restart and the docker operation hung waiting for them to reopen and they never would.

**- How I did it**
vi is my friend

**- How to verify it**
See bugzilla for test description.  To duplicate test one must 'setenforce 0' before running the script, that is not noted in the BZ.

**- Description for the changelog**
Fix for docker hang after restart when live-restore is configured

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by mbaldessari** [comment]
Thanks Tom! Am I missing something or is a file missing in this commit series?
rpm scratch build with the three commits here is failing with the following:
_build/src/github.com/docker/docker/daemon/logger/jsonfilelog/read.go:16:2: cannot find package "github.com/docker/docker/daemon/logger/jsonfilelog/multireader"

**Comment by runcom** [comment]
We talked yesterday and I believe he's about to fix that Michele

**Comment by mbaldessari** [comment]
Ack, you guys just give me a shout when ready and I will try and test this as much as I can

**Comment by TomSweeneyRedHat** [comment]
@mbaldessari OH SHOOT!  I forgot to include two files in this PR.  I'll got straighten that out.

**Comment by TomSweeneyRedHat** [comment]
@mbaldessari Just reposted with the missing files.  Sorry about the ooops!

**Comment by mbaldessari** [comment]
I dropped you a line. I built an rpm with these five commits but had no luck (i.e. issue is still there)? Not sure I missed something though

**Comment by rhatdan** [comment]
Tom could you squash your PRS?

**Comment by TomSweeneyRedHat** [comment]
PR's be squished.  Touched up the commit message too.

**Comment by mbaldessari** [comment]
I'll recap more in detail in the BZ, but initial testing looks good from my side as well. Thanks!

**Comment by rhatdan** [comment]
LGTM
@runcom PTAL

**Comment by runcom** [comment]
LGTM but I'd love @mbaldessari to LGTM this  after re-testing.

**Comment by rhatdan** [comment]
Merging.

**Comment by rhatdan** [comment]
@lsm5 can @fkluknav we get a new RHEL build for this?

**Pull request merged**
