### PR TITLE
Add MountLabel to diff and diffSize

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by rhatdan** [comment]
@rhvgoyal PTAL

**Comment by rhvgoyal** [comment]
@rhatdan I think this PR should be opened upstream and merged upstream first.

**Comment by rhatdan** [comment]
I agree although it will be very different there.  I just wanted you to take a look at it, it also has not been tested.

**Comment by rhvgoyal** [comment]
@rhatdan this is showing up a lot. Is there any chance you can open a PR for this upstream.

**Pull request closed without merging**
