### PR TITLE
Note API calls to syslog and the audit log

### PR DESCRIPTION
**Pull request by nalind**
Alec Benson's logging/audit patches, altered to wire the functionality in as a middleware function.

### CODE REVIEW

**Comment by rhatdan** [comment]
These patches do not apply to the fedora branch?

**Comment by nalind** [comment]
Okay, cleared merge conflicts and added a patch to build a dynamic binary for use when running the integration tests so that we don't hit RHBZ#1265409 in the EL7 glibc package.

**Comment by nalind** [comment]
Restarting as PR#131.

**Comment by nalind** [comment]
Whoops, closed the wrong one.

**Comment by nalind** [comment]
Rebased to just the pieces that are missing, and tweaked how we pass the UID along to hopefully avoid falsely attributing things to UID 0 in some cases.

**Comment by nalind** [comment]
Rebased.

**Comment by rhatdan** [comment]
LGTM

Merged.

**Comment by nalind** [comment]
A couple of bits seem to have been lost in the merge.  I've rebased them, and can open another PR if you don't have a way to reopen this one (I don't).

**Comment by jlebon** [comment]
Ahhh, yes that would explain it. I opened #5 when I saw a syntax error, but it's probably among the bits that were lost. Hmm, wonder how it got lost.

**Pull request closed without merging**
