### PR TITLE
Secrets rewrite

### PR DESCRIPTION
**Pull request by runcom**
This patch set reverts our original secret patch and rewrite it to play nice with swarm (introduced in 1.13.x, and swarm secrets).

Before merging this, we need a test build to run our docker autotest and all other tests we have in order to not regress on the secret patch.

@rhatdan @ddarrah  @lsm5 @cevich can you help with tihs?

Supposed to fix https://bugzilla.redhat.com/show_bug.cgi?id=1440389

### CODE REVIEW

**Comment by lsm5** [comment]
looking ..

**Comment by rhatdan** [comment]
@runcom have you tested this on a RHEL system and made sure that you can do a yum -y update inside of a RHEL container and get content?

**Comment by runcom** [comment]
@rhatdan I did, but I want to make sure all our QE tests pass before even thinking about merging this :)

**Comment by johnbieren** [comment]
aos-ci-test

**Comment by strigazi** [comment]
Tried to build locally, I'm getting the same 4 errors  shown at the Red Hat CI log.

**Comment by runcom** [comment]
> Tried to build locally, I'm getting the same 4 errors shown at the Red Hat CI log.

which one are those? if it's osx cross, you can comment out that section in the Dockerfile and re-try

**Comment by rhatdan** [comment]
@runcom have you verified that you can still install software with this patch change on a RHEL7 system?
yum -y install httpd works?

**Comment by runcom** [comment]
> @runcom have you verified that you can still install software with this patch change on a RHEL7 system?
> yum -y install httpd works?

@rhatdan I did, and it works, also asked @cevich to write an appropriate test for this in our docker autotest.

**Comment by runcom** [comment]
Let's pull this in

**Comment by rhatdan** [comment]
There looks like there might be a bug with microdnf not working. so this patch might need further work.  I am glad the patch is working now.  Lets get a build out for 7.3.5 release.

**Comment by runcom** [comment]
@rhatdan is this specific patch breaking microdnf or was the original secret patch breaking it as well?

**Comment by rhatdan** [comment]
No nothing to do with this patch as the old one was reported to not work.  I have asked them to create a bugzilla on this.

```

error:
sudo docker run --rm -ti registry.access.redhat.com/rhel7-atomic:7.3-15 microdnf --nodocs --enablerepo=rhel-7-server-rpms install tar
error: (--enablerepo) repo rhel-7-server-rpms not found

what works:
#dnf.repo is copy of redhat.repo
# sudo docker run --rm -v /etc/rhsm/ca/:/etc/rhsm/ca/ -v /etc/pki/entitlement/:/etc/pki/entitlement/ -v /etc/yum.repos.d/dnf.repo:/etc/yum.repos.d/dnf.repo -ti registry.access.redhat.com/rhel7-atomic:7.3-15 microdnf --nodocs --enablerepo=rhel-7-server-rpms install tar

Node is subscribed.
# subscription-manager repos --list-enabled
(Partial output)

+----------------------------------------------------------+
    Available Repositories in /etc/yum.repos.d/redhat.repo
+----------------------------------------------------------+
Repo ID:   rhel-7-server-rpms
Repo Name: Red Hat Enterprise Linux 7 Server (RPMs)
Repo URL:  https://XXXX
Enabled:   1

Repo ID:   rhel-7-server-extras-rpms
Repo Name: Red Hat Enterprise Linux 7 Server - Extras (RPMs)
Repo URL:  https://XXXX
Enabled:   1


Have a question?
First, check the FAQ: https://mojo.redhat.com/docs/DOC-943081
Next, check the archives: http://post-office.corp.redhat.com/archives/openshift-sme/

```

**Comment by runcom** [comment]
@rhatdan rigthw, just seen that, I'll assign the BZ to myself to look at this.

**Comment by cevich** [comment]
Ref: New test is here, about to be merged, final testing underway.

https://github.com/autotest/autotest-docker/pull/707#pullrequestreview-34095479

**Pull request merged**
