### PR TITLE
backport: No container locks on `docker ps`

### PR DESCRIPTION
**Pull request by kolyshkin**
## Problem

Our openshift-ci cluster was experiencing both long delays and lockups on `docker ps`. Investigation shown that, for the lockup case, all the instances of `daemon.Container()` (the API call producing the list of containers) are waiting for a lock for a particular container which was taken 2+ hours ago and never released. A long delay is also caused by waiting for the same lock, when some other container is performing a long operation (e.g. container creation, which includes selinux relabeling).

A typical waiting goroutine backtrace looks like this:

```
goroutine 145541 [semacquire, 153 minutes]:
sync.runtime_SemacquireMutex(0xc42031f7a4, 0x0)
        /opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc42031f7a0)
        /opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/sync/mutex.go:134 +0x108
github.com/docker/docker/daemon.(*Daemon).reducePsContainer(0xc420472200, 0xc42289d400, 0xc4242b6120, 0xc420b3d680, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/list.go:202 +0x46
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc420472200, 0xc4247c60c0, 0xc420b3d680, 0xc420b3d690, 0x1, 0x424858, 0x40, 0xc4214ce598)
        /builddir/build/BUILD/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/list.go:184 +0x12e
github.com/docker/docker/daemon.(*Daemon).Containers(0xc420472200, 0xc4247c60c0, 0x0, 0x0, 0x0, 0xed4d7ae6870956f6, 0x424858)
        /builddir/build/BUILD/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/list.go:107 +0x54
......
```

## Root cause

~~Alas, I was unable to find a place in the code which acquired but not released the lock, since there are way too many places like that in the code (and I'm still looking). Still, even if the bug will be found, `docker ps` can easily be stuck for a few minutes, since many container operations take this lock for this time.~~

A container being created got stuck on `getdents(2)` in the middle of selinux relabeling. This is most probably a volume on a networked block device (provided by GCE).

`daemon.(*Daemon).containerStart()` holds a per-container lock for the duration of the container creation.

Here's an except from dockerd goroutine dump:

```
goroutine 145539 [syscall, 138 minutes]:
syscall.Syscall(0xd9, 0x8a, 0xc423880000, 0x1000, 0xc4204f1200, 0xc4224c2c80, 0x640)
        /opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Getdents(0x8a, 0xc423880000, 0x1000, 0x1000, 0xc42576bc38, 0x18, 0xc42576bc30)
        /opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/syscall/zsyscall_linux_amd64.go:482 +0x5f
syscall.ReadDirent(0x8a, 0xc423880000, 0x1000, 0x1000, 0x15ccce0, 0x100000000000001, 0xc422a2dc00)
        /opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/syscall/syscall_linux.go:772 +0x49
internal/poll.(*FD).ReadDirent(0xc4219865a0, 0xc423880000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/internal/poll/fd_unix.go:404 +0xad
os.(*File).readdirnames(0xc42619ab40, 0xffffffffffffffff, 0x0, 0x0, 0xc42619ab40, 0x0, 0x0)
        /opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/os/dir_unix.go:67 +0x1bf
<...skipped....>
path/filepath.Walk(0xc4203fd400, 0x97, 0xc420ff4940, 0x0, 0xc42338c6d8)
        /opt/rh/go-toolset-1.10/root/usr/lib/go-toolset-1.10-golang/src/path/filepath/path.go:403 +0x106
github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/selinux.Chcon(0xc4203fd400, 0x97, 0xc421d6c510, 0x2f, 0x25aa601, 0x6e, 0x28)
        /builddir/build/BUILD/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/selinux/selinux.go:482 +0xc3
github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/label.Relabel(0xc4203fd400, 0x97, 0xc421d6c510, 0x2f, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/label/label_selinux.go:146 +0x1fb
github.com/docker/docker/volume.(*MountPoint).Setup.func1(0xc42338c908, 0xc4227a3680, 0xc42576c8f8, 0xc421d6c510, 0x2f)
        /builddir/build/BUILD/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/volume/volume.go:139 +0x1e0
github.com/docker/docker/volume.(*MountPoint).Setup(0xc4227a3680, 0xc421d6c510, 0x2f, 0x0, 0x0, 0xc4270424c0, 0xc4247ca790, 0x97, 0x0, 0x0)
        /builddir/build/BUILD/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/volume/volume.go:187 +0x447
github.com/docker/docker/daemon.(*Daemon).setupMounts(0xc420472200, 0xc42289d400, 0x0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/volumes_unix.go:58 +0x3be
github.com/docker/docker/daemon.(*Daemon).createSpec(0xc420472200, 0xc42289d400, 0x0, 0x0, 0xc420472200)
        /builddir/build/BUILD/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/oci_linux.go:703 +0xab2
github.com/docker/docker/daemon.(*Daemon).containerStart(0xc420472200, 0xc42289d400, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        /builddir/build/BUILD/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/start.go:149 +0x25d
github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc420472200, 0xc42565eb07, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x424858, 0x10)
        /builddir/build/BUILD/docker-b2f74b220126bddbae585cfe2406498ced3ae065/_build/src/github.com/docker/docker/daemon/start.go:87 +0x195
```

## Solution

It was not a great idea in the first place to take per-container locks for such frequently used and critical operation like `docker ps`. Thus here is a backport of upstream PR https://github.com/moby/moby/pull/31273 which removed the lock. It does not resolves the root cause (lock being held forever in case of I/O operation being stuck) but fixes the bad consequences (docker ps being stuck).

## Backport details

This was not an easy backport. Most of the merge conflicts were caused by old codebase here, but there were some caused by commits in this repo missed from upstream. Every cherry-pick that resulted in conflicts has them documented in the commit message.

The main strategy was to skip porting most of the preceding PRs and resolve the merge conflicts manually.

### Skipped PRs

These PRs were looked at carefully but not backported. The list is not complete, the order is random.

* https://github.com/moby/moby/pull/30117
* https://github.com/moby/moby/pull/29289
* https://github.com/moby/moby/pull/31996
* https://github.com/moby/moby/pull/32687
* https://github.com/moby/moby/pull/30117
* https://github.com/moby/moby/pull/27557
* https://github.com/moby/moby/pull/33241
* https://github.com/moby/moby/pull/33241
* https://github.com/moby/moby/pull/32336
* https://github.com/moby/moby/pull/29226
* https://github.com/moby/moby/pull/29963
* https://github.com/moby/moby/pull/29683

### Ported PRs

These were analysed and deemed to be a necessary prerequisites for the PR being backported.

* https://github.com/moby/moby/pull/30208 Remove sqlite dependency
* https://github.com/moby/moby/pull/30753 remove Register return value
* https://github.com/moby/moby/pull/29554 Use counter for tracking container states
* https://github.com/moby/moby/pull/30618 Fix some data races 
* https://github.com/moby/moby/pull/31159 Don’t hold container lock for size calculation 
* https://github.com/moby/moby/pull/33456 Lock container while connecting to a new network
* https://github.com/moby/moby/pull/31083 fix some typos from module contrib to man
* https://github.com/moby/moby/pull/32821 Fix issue backporting mount spec to pre-1.13 obj
* https://github.com/moby/moby/pull/33209 Add continue on error in mountspec backport 

### Finally:

* https://github.com/moby/moby/pull/31273 No container locks on `docker ps`

### CODE REVIEW

**Comment by kolyshkin** [comment]
That'd be nice to run CI overnight (at least to see the beast compiles)

**Comment by kolyshkin** [comment]
@rhatdan PTAL

**Comment by mrunalp** [comment]
@kolyshkin Were you able to run and smoke test this locally? We can ask for a auto-test run for a scratch build of this run.

**Comment by rhatdan** [comment]
LGTM

**Comment by kolyshkin** [comment]
Update: found a root cause, updated the description. This PR is still a valid workaround.

A solution would be to cancel container creation upon a timeout

**Comment by kolyshkin** [comment]
> A solution would be to cancel container creation upon a timeout

Which, of course, is also a workaround, just more targeted.

**Comment by kolyshkin** [comment]
Minor updates to PR description.

A docker build with this PR was tested by QE team (they have some smoke tests under their belt), and also live-tested in a production environment (OC CI cluster doing search). The issue appears to be resolved, and no regressions were observed.

@mrunalp PTAL

**Comment by mrunalp** [comment]
LGTM

**Comment by alibo** [comment]
is it also backported to docker-1.13.1 (centos 7)?
I've installed v1.13.1-203 and I'm still facing this issue.

**Pull request merged**
