### PR TITLE
repo: hook up to redhat-ci

### PR DESCRIPTION
**Pull request by jlebon**
Add a basic YAML file on which we can build upon.

### CODE REVIEW

**Comment by runcom** [comment]
@jlebon I'm ok to merge, do we need to wait for something?

**Comment by jlebon** [comment]
@runcom Let's make sure the tester does its job and can e.g. upload logs.
I'll take care of removing the old tester once we merge this in. :)

**Comment by jlebon** [comment]
@runcom I think this is ready to go now.

**Comment by runcom** [comment]
Alright, so, this yaml is ending up into the master branch but we don't carry our patches in the master branch. We have ad-hoc branches for each docker release with our patches (e.g. docker-1.12. 6).
We need to carry another patch for this yaml file to be integrated with our patches (and effectively kick the CI when someone pushes on those branches).
@jlebon if it's OK for you I'll cherry pick this commit into each of our branches. The CI should kick in when someone pushes on those branches right? Or, is it mandatory to have this file in the master branch?

**Comment by jlebon** [comment]
Right, you'll have to include this in every branch for which you'd like PRs to be tested.

**Comment by jlebon** [comment]
A clearer way to say this: the branch against which a PR is opened needs to have that `.redhat-ci.yml` file if you'd like that PR to be tested.

**Comment by runcom** [comment]
Alright, I'll leave this open to remind me to carry this commit into our branches. I'll do this later today though so people can start doing stuff on top of this new CI soon.

**Comment by jlebon** [comment]
Sounds good, I'll take care of tearing down the other tester in the meantime.

**Comment by runcom** [comment]
cherry-picked this commit into docker-1.12.6, docker-1.13, docker-1.13.1, docker-1.14.0

**Pull request closed without merging**
