### PR TITLE
Updated libcontainer/user so that numeric users are treated as uid

### PR DESCRIPTION
**Pull request by mrunalp**
@rhatdan @runcom @lsm5 PTAL

This is the port to Fedora 1.10

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
@rhatdan @mrunalp does this need to be ported to rhel branch?

**Comment by rhatdan** [comment]
Yes I thought it already was.

**Comment by rhatdan** [comment]
runcom we want everything the same between RHEL and Fedora going forward.

**Comment by runcom** [comment]
Yep :)

**Comment by runcom** [comment]
I didn't find this commit in rhel7-1.10.3 branch - I've cherry picked it though

**Comment by rhatdan** [comment]
Great.

**Pull request merged**
