### PR TITLE
BACKPORT: Move prestart hooks after container mounts

### PR DESCRIPTION
**Pull request by mrunalp**
@rhatdan @runcom PTAL

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
:+1:

**Comment by runcom** [comment]
applied this patch to fedora-1.10.3 branch, all good with tests

**Comment by rhatdan** [comment]
runcom lets get the patch I just submitted to fix the location of the oci-hooks, they are installed in /usr/libexec/oci/hooks.d

Then we can get a build going for Fedora-24, and Rawhide and Eventually RHEL.

**Comment by runcom** [comment]
What about Fedora 23? Right now the 23 spec use docker 1.10.2 and it's in updates-testing

**Comment by runcom** [comment]
I'll take care of f24 and rawhide, @lsm5 could have a look at f23 and rhel also? The novolume plugin also needs to be updated in f23 but we were holding any f23 spec update because of Jhon'# journald work

**Comment by rhatdan** [comment]
Yes back port it there, all should use the same version of docker-1.10.  Right now the oci- hooks packages are only available in F24 and Rawhide.

**Comment by runcom** [comment]
Right, F24 and Rawhide have also `Recommends: oci-register-machine` - should I add `Recommends: oci-systemd-hook` also?

**Comment by rhatdan** [comment]
Yes

**Comment by runcom** [comment]
done, I'm updating rawhide and f24 right now

**Pull request merged**
