### PR TITLE
Fix some test errors encountered on the fedora-1.9 branch

### PR DESCRIPTION
**Pull request by jlebon**
This fixes a few of the failures reported in RHBZ1271334. Most were due to the fact that the busybox image used for testing was incompatible with the secrets patch. See commit message of the first patch for more details.

### CODE REVIEW

**Comment by jlebon** [comment]
@rhatdan @sallyom This should fix the weird `/var` to `/tmp` behaviour.

**Comment by rhatdan** [comment]
@jlebon Could you send the busybox change to upstream.  Thanks for figuring this out.  I had no idea.

@mrunalp PTAL

**Comment by rhatdan** [comment]
merged, into existing patches.

**Comment by mrunalp** [comment]
Good catch! Lgtm

**Comment by sallyom** [comment]
I don't want to speculate on how long that may have taken me to figure out.  
DockerSuite.TestBindMounts and DockerSuite.TestDiffEnsureOnlyKmsgAndPtmx  are now passing on my end.  :)  moving on...

**Comment by rhatdan** [comment]
Excellent, Any other bugs?

**Comment by sallyom** [comment]
yes there are, i'm running make test-integration-cli now, i'll let you know.
I'm looking at this now:

FAIL: docker_cli_run_test.go:3494: DockerSuite.TestContainerRestartInMultipleNetworks
docker_cli_run_test.go:3516:
    c.Assert(err, check.NotNil)
... value = nil

https://github.com/projectatomic/docker/blob/master/integration-cli/docker_cli_run_test.go#L3510
I ran this test on my system and indeed, I get no error when I try to docker exec ping w/stopped container.  (#L3529)  Something with https://github.com/rhatdan/docker/commit/db0b5752ee19f049d928820f2fffef21a35a757b?

**Pull request closed without merging**
