### PR TITLE
daemon: support default pids limit

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

**- What I did**

set default pids limit on daemon level

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by runcom** [comment]
@mrunalp @rhatdan ptal

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
LGTM

**Comment by ejc3** [comment]
The new default being 4096 bit us. It would be helpful to mention what the new default is in the release notes. Thanks!

**Pull request merged**
