### PR TITLE
BACKPORT: Fix for --cgroup-parent in docker

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom @rhatdan PTAL

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
For some reason this disappeared from 1.9.

**Comment by mrunalp** [comment]
cc: @derekwaynecarr

**Comment by derekwaynecarr** [comment]
What happens if you specify a slice that does not exist or does not have a
configured unit?  Do you get a transient slice?

For example, if I docker run --cgroup-parent=foo-bar.slice nginx will I get
new transient slices defined for foo.slice and foo-bar.slice?

Can we get this packaged for fedora 23, etc?  I am working on cards that
need this feature.

**Comment by mrunalp** [comment]
@derekwaynecarr It should create that slice and the scope under that.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
