### PR TITLE
BACKPORT: Synchronize writes to mcs map

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@rhatdan @runcom PTAL

**Comment by runcom** [comment]
LGTM

**Comment by rhatdan** [comment]
Nice LGTM

**Comment by mrunalp** [comment]
@runcom Can you merge this? We need this in the next rpm.

**Comment by runcom** [comment]
@mrunalp done

**Comment by mrunalp** [comment]
@runcom Thanks!

**Pull request merged**
