### PR TITLE
Backport of systemd cgroup parent support in docker

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM, do we want this for Fedora or just for RHEL?

**Comment by mrunalp** [comment]
We need it for RHEL as well. I will open a PR for that.

**Comment by rhatdan** [comment]
Wait for docker-1.10

**Pull request closed without merging**
