### PR TITLE
default to slave mounting

### PR DESCRIPTION
**Pull request by runcom**
same as #158 and #159 but for fedora

@rhatdan @rhvgoyal PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM. first half should probably go upstream.   No reason to ever propagate those.  Also can you propagate file mounts?

**Comment by runcom** [comment]
What do you mean by propagate file file mounts? It should be already handled - however this pr is not finished nor the linked one for rhel, working to fix all the tests and some errors spotted. 

I'll work out a patch for upstream for the network file to be private by default

**Comment by runcom** [comment]
> LGTM. first half should probably go upstream. No reason to ever propagate those.

upstream already has `rprivate` for those files since it's default to be rprivate everywhere

**Comment by rhvgoyal** [comment]
Right, upstream already has rprivate for all volumes as default is rprivate. So I don't think there is a need to push anything upstream.

**Pull request merged**
