### PR TITLE
Backport go1.6 fixes rhel

### PR DESCRIPTION
**Pull request by runcom**
same as https://github.com/projectatomic/docker/pull/112 but for rhel7 branch

### CODE REVIEW

**Comment by runcom** [comment]
@rhatdan @mrunalp PTAL

**Comment by rhatdan** [comment]
I don't think we are building with golang 1.6 yet on rhel.  Will need this for the rhel7.2.5 release or rhel7.3 release.

**Comment by runcom** [comment]
Either way, this backport patch doesn't apply anything new, it's just go1.6 compatible

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
ping @mrunalp to merge

**Comment by mrunalp** [comment]
LGTM

**Comment by mrunalp** [comment]
@runcom I don't have merge access to this repo :/

**Pull request merged**
