### PR TITLE
Update containers/image for Openshift signatures extension

### PR DESCRIPTION
**Pull request by runcom**
@mtrmac PTAL - this brings docker-1.12.6 in line with 1.13.1 and 17.03.1-ce

### CODE REVIEW

**Comment by mtrmac** [comment]
Sure, the c/image rebase looks plausible.

**Comment by rhatdan** [comment]
Should we merge this?

**Comment by runcom** [comment]
@rhatdan I would not, not sure what @mtrmac feels about this :)

**Comment by mtrmac** [comment]
_Eventually_ we should definitely rebase to bring in the signatures extension.

If the question is about merging into that specific branch, this is aligned with Origin 1.5, released on Apr 21. (And I don’t know how that projecatomic/docker branch maps into a specific stability promise or RHEL stream.)

**Comment by runcom** [comment]
This has been pulled in 1.12.x already

**Pull request closed without merging**
