### PR TITLE
fix go-lint, go-vet errors

### PR DESCRIPTION
**Pull request by sallyom**
Signed-off-by: Sally O'Malley <somalley@redhat.com>

### CODE REVIEW

**Comment by sallyom** [comment]
@rhatdan please check the comments added to satisfy go-lint errors, they might need re-wording, thanks.

**Comment by rhatdan** [comment]
Sally, I need these done on individual patches rather then all in one patch.  IE I need a patch to fix the audit code and one to fix the gen_dockerfile code ...

**Comment by sallyom** [comment]
@rhatdan, ok, i'll do that

**Comment by sallyom** [comment]
closing this, opened separate PRs #134, #135, #136, #137

**Pull request closed without merging**
