### PR TITLE
docker info doesn't show Backing Filesystem

### PR DESCRIPTION
**Pull request by runcom**
Problem:
-----------
`docker info` only shows `Backing Filesystem` the first time you start a daemon. Every later restart makes the value became empty.

First time you run a daemon:
```
[root@localhost docker]# docker info
Containers: 0
Images: 0
Server Version: 1.10.0-dev
Storage Driver: devicemapper
 Pool Name: docker-252:3-8464477-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 53.74 MB
 Data Space Total: 107.4 GB
 Data Space Available: 3.213 GB
 Metadata Space Used: 606.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/0.0/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/0.0/devicemapper/devicemapper/metadata
 Library Version: 1.02.113 (2015-12-05)
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-0.rc4.git2.1.fc24.x86_64
Operating System: Fedora 24 (Rawhide)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 0
CPUs: 1
Total Memory: 973.2 MiB
Name: localhost.localdomain
ID: 4G4C:VRMN:JJSZ:2MVU:PCQD:WQI3:ZD7Y:DBN5:XMMV:UH6G:KX2J:KYPR
Experimental: true
Registries: 127.0.0.0/8 (insecure), docker.io (secure)
```
Restart the daemon (notice how Backing Filesystem is emtpy):
```
[root@localhost docker]# docker info
Containers: 0
Images: 0
Server Version: 1.10.0-dev
Storage Driver: devicemapper
 Pool Name: docker-252:3-8464477-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 53.74 MB
 Data Space Total: 107.4 GB
 Data Space Available: 3.213 GB
 Metadata Space Used: 606.2 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/0.0/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/0.0/devicemapper/devicemapper/metadata
 Library Version: 1.02.113 (2015-12-05)
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-0.rc4.git2.1.fc24.x86_64
Operating System: Fedora 24 (Rawhide)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 0
CPUs: 1
Total Memory: 973.2 MiB
Name: localhost.localdomain
ID: 4G4C:VRMN:JJSZ:2MVU:PCQD:WQI3:ZD7Y:DBN5:XMMV:UH6G:KX2J:KYPR
Experimental: true
Registries: 127.0.0.0/8 (insecure), docker.io (secure)
```
Reproduction
------
OS: Fedora Rawhide which just use devmapper as default and xfs

1) `dnf install docker` (this will install out latest fedora-1.10 branch)
2) `systemctl start docker`
3) `docker info` (this will show xfs as backing filesystem)
4) `systemctl restart docker`
5) `docker info` (this WON'T show xfs as backing filesystem)

You can actually reproduce it even after the very first daemon startup:

1) `systemctl stop docker`
2) `rm -rf /var/lib/docker`
3) `systemctl start docker`
4) `docker info` (this will show xfs as backing filesystem)
5) `systemctl restart docker`
6) `docker info` (this WON'T show xfs as backing filesystem)

Thoughts
----
My patch basically is recording the base device filesystem bacause upon code inspection it seems it isn't recorded anywhere so I put it in the metadata and for backward compatibilty I do some checks at initialization time. This patch IS fixing this problem
But
---
~~Building and running a docker dynbinary from docker/docker master branch doesn't have this issue, and this is so weird because our fedora-1.10 branch is based on that official branch.
I first thought some of the patches we're carrying are breaking this but I can't find why (if any)~~

### CODE REVIEW

**Comment by runcom** [comment]
ping @rhatdan @rhvgoyal should I open a bugzilla?

**Comment by runcom** [comment]
EDIT
--
This problem is present in docker/docker master as well, I'll move the discussion there at https://github.com/docker/docker/pull/18606

I'll close this one

**Comment by rhatdan** [comment]
yes open a bugzilla on RHEL so we can track this.

**Comment by runcom** [comment]
PR merged upstream, does this still need a bugzilla?

**Comment by rhatdan** [comment]
Yes just to let qe know to test it.

**Comment by rhatdan** [comment]
After you make the bugzilla, mark it as modified and fixed in docker-1.10.  Is this worth back porting to docker-1.9?  I doubt it.

**Comment by runcom** [comment]
@rhatdan same, I don't think it needs a backport..It's something pretty specific to people mounting docker socket

**Pull request closed without merging**
