### PR TITLE
Fixes for reading from the journald log driver

### PR DESCRIPTION
**Pull request by nalind**
This is the set of fixes being proposed for https://bugzilla.redhat.com/show_bug.cgi?id=1314463, which fix a couple of race conditions and improve error reporting when we're reading from the journald log driver.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by runcom** [comment]
@nalind this needs to be applied on rhel7-1.9 also right? seems like I cannot patch it cleanly, could you open a PR against rhel7-1.9 also?

**Comment by nalind** [comment]
Yes, I hadn't realized they were drifting apart.

**Comment by nalind** [comment]
Opened #86.

**Comment by rhatdan** [comment]
I have a feeing docker-1.9 for RHEL has sailed.  I don't see this getting in, or us stopping shipping for this fix.  If this is a problem for a customer they can just use dockers logging.

**Comment by runcom** [comment]
we should probably revert https://github.com/projectatomic/docker/pull/86 then and get @mrunalp's patch only

**Comment by runcom** [comment]
we'll keep the patch in fedora though, right?

**Comment by rhatdan** [comment]
Yes we should fix fedora, but I am thinking that nothing new is going to get into rhel, at most we should just add mrunals patch anything else would need to be tested.  I have a feeling we will not add anything.

**Pull request merged**
