### PR TITLE
make error value work on 32-bit

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@rhatdan PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
@nalind are those errors something related to __udivdi3 defined twice?

**Comment by lsm5** [comment]
rebased on projectatomic/fedora-1.10.

**Comment by nalind** [comment]
@lsm5 Yup.  I could suppress those with -ldflags "-linkmode external -extldflags zmuldefs", but would have to take care that using that option wasn't also papering over a different problem where muldefs would be a mistake.

**Comment by rhatdan** [comment]
I have fixed the code to return -1.

**Comment by rhatdan** [comment]
Lokesh could you check if that fixes your problem and then close this if it does.

**Comment by lsm5** [comment]
-1 does get over this issue. closing ..

nalin thanks for the -ldflags ... 

That's been an issue on i386 for sometime now. Do you have a patch ready for it that you could send over?

**Comment by nalind** [comment]
I messed around a bit and found that passing them in by overriding LDFLAGS_STATIC_DOCKER in hack/make/dynbinary does the trick.  Sent an actual patch via email.

**Pull request closed without merging**
