### PR TITLE
Docfix "docker search"

### PR DESCRIPTION
**Pull request by tnguyen-rh**
Most of the changes are to update the output of the example `docker search` command.  In only one instance was the output left intact and the command modified to insert `--no-index`.

As this is my first PR to projectatomic/docker, i'm taking the "baby steps" approach:
- I have not squashed.
- If/When the changes are approved, i will squash, aggregating the individual commit messages into a list of changes in the squashed commit message.
Is that OK?  Any hints on process/workflow very much appreciated.

### CODE REVIEW

**Comment by rhatdan** [comment]
bot, add author to whitelist

**Comment by rhatdan** [comment]
Could you put these all in one pull request.  Then I will merge.  Thanks.

**Comment by tnguyen-rh** [comment]
@rhatdan Done.

**Comment by rhatdan** [comment]
I merged this change and combined it with the original patch.  @runcom Please add this to your patches also.

**Comment by runcom** [comment]
Will do thx Dan

**Comment by tnguyen-rh** [comment]
The contents of this patch are now merged into branch [rhel7-1.10](https://github.com/projectatomic/docker/commits/rhel7-1.10)  as of https://github.com/projectatomic/docker/commit/6013c2d2ccc3d9b10bb856de722a5bcd6d22193f so, deleting this branch.

**Pull request closed without merging**
