### PR TITLE
Prevent unnecessary blob uploads

### PR DESCRIPTION
**Pull request by miminar**
Backporting upstream docker/docker#26564

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1372065

### CODE REVIEW

**Comment by runcom** [comment]
@miminar we don't need this for rhel7-1.11 - we skipped that in both rhel and fedora, we just need 1.12

**Comment by miminar** [comment]
@runcom I see neither `rhel7-1.12` nor `fedora-1.12` branch in `projectatomic/docker`. There's only `docker-1.12`. I'll backport it at least to `rhel7-1.10`.

**Comment by runcom** [comment]
Yeah, we need this just for rhel7-1.10.3 _and_ docker-1.12

**Comment by miminar** [comment]
@runcom I see, thanks. Opened #202 and #203 for mentioned branches. Closing this.

**Pull request closed without merging**
