### PR TITLE
BACKPORT: Expand slice path correctly for nested systemd cgroup

### PR DESCRIPTION
**Pull request by mrunalp**
@runcom @rhatdan PTAL

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Is there a plan to add unit testing around this whole file upstream:

https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go#L337

I agree this should fix the solution, but we should really have more unit tests in the libcontainer cgroup package that verifies this stuff.

**Comment by runcom** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
I was directed to an automated test that will cover this, LGTM

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
