### PR TITLE
Remove "Fixed docker's authentication issue" patch

### PR DESCRIPTION
**Pull request by runcom**
This reverts commit 3c8707b76809f622783abfcba3275303b88de1d5 and remove patch explaination from readme
So this removes one of the pathes we are carrying, work will be done the same for 1.10 once I implement additional registries auth :) :) :)

The patch isn't needed anymore because now before any `registry.NewSession` we resolve the correct authConfig for the given server or empty out the authConfig

### CODE REVIEW

**Comment by runcom** [comment]
@rhatdan :)

**Comment by rhatdan** [comment]
Ok I removed this from docker-1.10 also.

**Comment by runcom** [comment]
@rhatdan No, it can't be removed right now from docker-1.10 it needs auth support for default registries which is in the Backlog on trello (see my previous email)

**Comment by rhatdan** [comment]
I have removed  it, but I won't have @lsm5 build it until we have the new patch done.

**Comment by runcom** [comment]
@rhatdan ok, I moved the card from the Backlog to Next, so I'll be doing it the next week

**Comment by runcom** [comment]
I'll close this as well since you removed the patch, thx

**Pull request closed without merging**
