### PR TITLE
Fix mount propagation for host on private

### PR DESCRIPTION
**Pull request by runcom**
@rhvgoyal @rhatdan PTAL

based on discussion in https://github.com/projectatomic/docker/pull/158

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
this fixes my integration tests issue

**Comment by runcom** [comment]
@rhvgoyal getting lots of test failures:
```
PASS: docker_cli_build_test.go:6593: DockerSuite.TestBuildSymlinkBasename	0.711s
PASS: docker_cli_build_test.go:5045: DockerSuite.TestBuildSymlinkBreakout	0.557s
PASS: docker_cli_build_test.go:6448: DockerSuite.TestBuildTagEvent	0.568s
PASS: docker_cli_build_test.go:2012: DockerSuite.TestBuildUser	1.125s
PASS: docker_cli_build_test.go:3855: DockerSuite.TestBuildUsersAndGroups	12.408s
PASS: docker_cli_build_test.go:4761: DockerSuite.TestBuildVerboseOut	0.551s
PASS: docker_cli_build_test.go:3360: DockerSuite.TestBuildVerifyIntString	0.300s
PASS: docker_cli_build_test.go:4739: DockerSuite.TestBuildVerifySingleQuoteFails	0.734s
PASS: docker_cli_build_test.go:5552: DockerSuite.TestBuildVolumeFileExistsinContainer	0.709s
PASS: docker_cli_build_test.go:5127: DockerSuite.TestBuildVolumesRetainContents	1.353s

----------------------------------------------------------------------
FAIL: docker_cli_build_test.go:6658: DockerSuite.TestBuildWithBindMounts

docker_cli_build_test.go:6674:
    c.Assert(err, check.IsNil, check.Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc8204c7d20)} ("exit status 1")
... Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> d9551b4026f0
Step 2 : RUN cat /test/file
 ---> Running in 62e68e1068bb
Cannot start container 62e68e1068bb604dde7b79b57d32372b58657d31a9426b04f519757314ba3f3a: Path /tmp/test035520812 is mounted on /tmp but it is not a shared or slave mount.



----------------------------------------------------------------------
FAIL: docker_cli_build_test.go:6678: DockerSuite.TestBuildWithBindMountsFile

docker_cli_build_test.go:6694:
    c.Assert(err, check.IsNil, check.Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc8201eb760)} ("exit status 1")
... Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> d9551b4026f0
Step 2 : RUN cat /file
 ---> Running in 359fa10f5e98
Cannot start container 359fa10f5e984c7d6bb9a94532a04047dfa6934f4f72f01c4f7576b280f4ad0f: Path /tmp/test773701787/file is mounted on /tmp but it is not a shared or slave mount.



----------------------------------------------------------------------
PASS: docker_cli_build_test.go:6698: DockerSuite.TestBuildWithBindMountsNoVolume	0.028s

----------------------------------------------------------------------
FAIL: docker_cli_build_test.go:6732: DockerSuite.TestBuildWithBindMountsNotPersistedDir

docker_cli_build_test.go:6748:
    c.Assert(err, check.IsNil, check.Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc82057e020)} ("exit status 1")
... Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> d9551b4026f0
Step 2 : RUN cat /test/file
 ---> Running in ac271ba040ba
Cannot start container ac271ba040ba953dad4433bc83eb90640ff8d9c83bec2673d592dab6544f1f33: Path /tmp/test871705406 is mounted on /tmp but it is not a shared or slave mount.



----------------------------------------------------------------------
FAIL: docker_cli_build_test.go:6709: DockerSuite.TestBuildWithBindMountsNotPersistedFile

docker_cli_build_test.go:6725:
    c.Assert(err, check.IsNil, check.Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc8201e3ba0)} ("exit status 1")
... Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> d9551b4026f0
Step 2 : RUN cat /file
 ---> Running in 947aa2fa8d15
Cannot start container 947aa2fa8d15ee3c3d6b4694f0d42a7bd0a5786193175f1fdaf2a6bc4d894c79: Path /tmp/test732285317/file is mounted on /tmp but it is not a shared or slave mount.



----------------------------------------------------------------------
FAIL: docker_cli_build_test.go:6755: DockerSuite.TestBuildWithBindMountsReadOnlyDefault

docker_cli_build_test.go:6772:
    c.Assert(out, checker.Contains, "Read-only file system")
... obtained string = "" +
...     "Sending build context to Docker daemon 2.048 kB\r\r\n" +
...     "Step 1 : FROM busybox\n" +
...     " ---> d9551b4026f0\n" +
...     "Step 2 : RUN echo \"test\" > /test/file\n" +
...     " ---> Running in 78da3320dcb8\n" +
...     "Cannot start container 78da3320dcb87229aa8e1bbb3816926f1ca94a213e670841c322d099d211f97c: Path /tmp/test181580064 is mounted on /tmp but it is not a shared or slave mount.\n"
... substring string = "Read-only file system"


----------------------------------------------------------------------
FAIL: docker_cli_build_test.go:6775: DockerSuite.TestBuildWithBindMountsWarnOnReadWrite

docker_cli_build_test.go:6791:
    c.Assert(err, check.IsNil, check.Commentf(out))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc82023c960)} ("exit status 1")
... Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> d9551b4026f0
Step 2 : RUN cat /test/file
 ---> [Warning] bind mount mode is read-write for /tmp/test131379711:/test/:rw,Z, it will be changed to read-only
 ---> Running in fac4e605f0c7
Cannot start container fac4e605f0c7a02ad8843ddb8a4ef2764584aeb60ea618138661209c7f3a0872: Path /tmp/test131379711 is mounted on /tmp but it is not a shared or slave mount.



----------------------------------------------------------------------
PASS: docker_cli_build_test.go:2523: DockerSuite.TestBuildWithCache	0.496s
PASS: docker_cli_build_test.go:1713: DockerSuite.TestBuildWithInaccessibleFilesInContext	0.433s
PASS: docker_cli_build_test.go:4779: DockerSuite.TestBuildWithTabs	0.537s
PASS: docker_cli_build_test.go:5289: DockerSuite.TestBuildWithTwoDockerfiles	0.471s
PASS: docker_cli_build_test.go:3074: DockerSuite.TestBuildWithVolumeOwnership	1.038s
PASS: docker_cli_build_test.go:1945: DockerSuite.TestBuildWithVolumes	0.552s
PASS: docker_cli_build_test.go:2549: DockerSuite.TestBuildWithoutCache	0.680s
PASS: docker_cli_build_test.go:2060: DockerSuite.TestBuildWorkdirWithEnvVariables	1.026s
PASS: docker_cli_build_test.go:5097: DockerSuite.TestBuildXZHost	1.730s
PASS: docker_cli_proxy_test.go:12: DockerSuite.TestCliProxyDisableProxyUnixSock	0.140s
PASS: docker_cli_run_test.go:3943: DockerSuite.TestCmdCannotBeInvoked	0.468s
PASS: docker_cli_commit_test.go:10: DockerSuite.TestCommitAfterContainerIsDone	0.544s
PASS: docker_cli_commit_test.go:110: DockerSuite.TestCommitChange	0.728s
PASS: docker_cli_commit_test.go:70: DockerSuite.TestCommitHardlink	0.821s
PASS: docker_cli_commit_test.go:151: DockerSuite.TestCommitMergeConfigRun	0.787s
PASS: docker_cli_commit_test.go:58: DockerSuite.TestCommitNewFile	0.785s
PASS: docker_cli_commit_test.go:41: DockerSuite.TestCommitPausedContainer	0.457s
PASS: docker_cli_commit_test.go:90: DockerSuite.TestCommitTTY	0.811s

----------------------------------------------------------------------
FAIL: docker_cli_commit_test.go:100: DockerSuite.TestCommitWithHostBindMount

docker_cli_commit_test.go:102:
    dockerCmd(c, "run", "--name", "bind-commit", "-v", "/dev/null:/winning", "busybox", "true")
/go/src/github.com/docker/docker/pkg/integration/dockerCmd_utils.go:35:
    c.Assert(err, check.IsNil, check.Commentf("%q failed with errors: %s, %v", strings.Join(args, " "), out, err))
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc8205f5b80)} ("exit status 125")
... "run --name bind-commit -v /dev/null:/winning busybox true" failed with errors: docker: Error response from daemon: Cannot start container f0dda4ab9047de627ace475b19cd4b336a605d6950dc8a3b90d12288a6b6213b: Path /dev/null is mounted on /dev but it is not a shared or slave mount..
, exit status 125


----------------------------------------------------------------------
PASS: docker_cli_commit_test.go:25: DockerSuite.TestCommitWithoutPause	0.494s
PASS: docker_cli_config_test.go:64: DockerSuite.TestConfigDir	0.173s
PASS: docker_cli_config_test.go:18: DockerSuite.TestConfigHttpHeader	0.033s
PASS: docker_cli_netmode_test.go:52: DockerSuite.TestConflictContainerNetworkAndLinks	0.067s
PASS: docker_cli_netmode_test.go:62: DockerSuite.TestConflictNetworkModeAndOptions	0.277s
PASS: docker_api_containers_test.go:552: DockerSuite.TestContainerApiBadPort	0.001s
```

**Comment by runcom** [comment]
the whole rslave default mount seems to also break https://github.com/projectatomic/docker/commit/94578df0fc6db7acd4b8d707b2dc665b8b9be6ba (see tests above)

**Comment by rhvgoyal** [comment]
@runcom, more of same failures. More volumes are being mounted as "slave" but their parents mounts of type are "private". And I think this happens because if we are testing inside ubuntu environment, / their is private by default and that ensures child mounts are private by default.

IOW, I think you will have to modify failing tests and fix their volumes being mounted in to be of type "slave".

**Comment by runcom** [comment]
@rhvgoyal - I'm testing inside Fedora 23 - the tests just bin mount /tmp/path which is mounted in /tmp and we get that error

**Comment by rhvgoyal** [comment]
@runcom, On my fedora 24 box, /tmp is a "shared" mount. Can you run "findmnt -o TARGET,PROPAGATION /tmp" and see what kind of propagation property this mount has.

**Comment by runcom** [comment]
@rhvgoyal:
```
$ findmnt -o TARGET,PROPAGATION /tmp
TARGET PROPAGATION
/tmp   shared
```

**Comment by rhvgoyal** [comment]
@runcom, did you run this inside the F23 container? I am assuming that this is docker in docker where F23 image is launched and then docker is run inside. If that's the case then propagation properties of /tmp inside F23 container matters.

**Comment by runcom** [comment]
took care of all the errors and tests failure by adding `rprivate` to binds, thx @rhvgoyal 

@rhatdan @rhvgoyal PTAL

**Comment by rhvgoyal** [comment]
Existing volumes are all private by default. So this patch LGTM. Can't see how converting those existing voumes to use "rprivate" will break things.

**Comment by runcom** [comment]
@rhvgoyal last question: there's other code referring to this mount propagation stuff which I'm not sure of https://github.com/projectatomic/docker/commit/a2dc4f79f260247afe55ab7117c9de02a769d883#diff-e25aebb8373cdbf4e75ed6f2f0574d05R363

do we need to change something there?

**Comment by rhvgoyal** [comment]
@runcom, I believe that we don't require a change there.

**Comment by runcom** [comment]
awesome, I'll merge after tests and validations are ok, thanks again for taking the time to help here, much appreciated :)

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
