### PR TITLE
Remote repo inspection patch shrink

### PR DESCRIPTION
**Pull request by runcom**
This patch removes the tags endpoint from the old patch

~~I'd wait @rhatdan to first cherry-pick https://github.com/projectatomic/docker/pull/44 and then I'll go ahead and rebase this branch so Dan can cherry-pick the shrinked patch here.~~

@rhatdan there's a new branch in upstream docker to rebase onto also (then we can branch out to docker-1.11):
```
 * [new branch]      release/v1.10 -> upstream/release/v1.10
```

@miminar PTAL

### CODE REVIEW

**Comment by miminar** [comment]
Removing the `tags` endpoint is fine with me. :+1:

**Comment by rhatdan** [comment]
#44 is merged.

**Comment by runcom** [comment]
@rhatdan I'm rebasing

**Comment by runcom** [comment]
@rhatdan rebased, you can remove the last commit from branch `rhel7-1.10` and cherry-pick my commit here

**Comment by runcom** [comment]
@rhatdan https://github.com/runcom/docker/commit/362cd0773a4975d28042eb4305cb7e3b279ef04f can be still cherry-picked (after removing the last commit)

**Comment by rhatdan** [comment]
Merged.

**Pull request closed without merging**
