### PR TITLE
Fixups for exposing configured registrires

### PR DESCRIPTION
**Pull request by runcom**
As per this trello card: https://trello.com/c/UqPK03Fb/49-remote-image-inspect-patch-to-expose-additional-registries-via-rest-api-in-our-docker

ping @rhatdan this should be edited in `--add-registry` patch

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
If it is OK with @miminar I will merge.

**Comment by runcom** [comment]
@rhatdan I did the original work here for exposing additional registries, this is just a fix to avoid showing `--insecure-registriy`(s) which is wrong

**Comment by runcom** [comment]
Fixed

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
fixed michal's suggestions

**Comment by miminar** [comment]
Thanks, LGTM

**Comment by runcom** [comment]
I think @rhatdan integrated the previous commit though :P

**Comment by rhatdan** [comment]
What am I missing?

**Comment by runcom** [comment]
you didn't import https://github.com/runcom/docker/commit/37b65ecb5dd376faa71ef50cc6df3a372c781d5b because I push forced after michal suggestions, but nothing really important, I'll defer this small fix for another patch, don't worry, I'm closing this now, thx

**Pull request closed without merging**
