### PR TITLE
Don't set label for mqueue when user namespaces are enabled

### PR DESCRIPTION
**Pull request by mrunalp**
We can't modify the order of cloning/unsharing namespaces in go internal
library so we have to live with not labeling mqueue for this version.
This is being fixed in upstream version of runc that doesn't
have the same limitation.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

@rhatdan @runcom PTAL

### CODE REVIEW

**Comment by runcom** [comment]
Sounds good to me (based on the comments on the BZ also)

**Comment by runcom** [comment]
need to port this to fedora-1.10.3 also (taking care of it)

**Comment by runcom** [comment]
cherry-picked into fedora branch also

**Comment by mrunalp** [comment]
Thanks!

**Pull request merged**
