### PR TITLE
No dockerfile volume

### PR DESCRIPTION
**Pull request by runcom**
Prevents running containers from images that have been built from a
Dockerfile which was using the VOLUME instruction. The feature is
opt-in, otherwise it will continue to work with the normal behavior.
docker run will error out when trying to run a container from an image
while docker build will warn if building an image with a VOLUME
instruction.
Bind mounts will keep working if they override VOLUME(s) defined in an
image given no other VOLUME(s) are defined.

### CODE REVIEW

**Comment by rhvgoyal** [comment]
So we put the restriction during container start time and not container create time. And i am assuming it is done because somebody might restart docker daemon with different options and images with volumes are allowed now. And that seems to be the reason that you allow building images with volumes even if running containers of those images will not be allowed. Makes sense.

**Comment by rhatdan** [comment]
Merged into rhel7-1.10 and fedora-1.10

**Comment by runcom** [comment]
Exactly, build with volume is fine even if this new flag is passed at daemon startup, the build will just warn saying you won't be able to run the  image

**Comment by runcom** [comment]
@rhvgoyal do you think it will cause harm that I've not moved the img.Config check under removalInProgress as you suggested here https://github.com/projectatomic/docker/pull/22#commitcomment-14765404?

(I'm asking because it's merged now so maybe it's worth a follow up PR)

**Comment by rhvgoyal** [comment]
@runcom, I guess it should be ok. Can't think of anything very bad. If container was running to begin
with, that means it did not have volume. So image volume check will be negative anyway.

Probably you can change it in the PR you generate upstream.

**Pull request closed without merging**
