### PR TITLE
[docker-1.12-2] Signature verification on pull 

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mrunalp PTAL

**Comment by runcom** [comment]
DO NOT MERGE - needs projectatomic/docker#200 first so that I can fix this patch when that is fully fixed (missing containers/image re-vendor here!)

**Comment by runcom** [comment]
DO NOT MERGE

**Comment by runcom** [comment]
This PR is good to go, this is the same as #200 but for docker-1.12.2 (I will soon cherry-pick this same commit to the upcoming docker-1.12.3 when upstream goes GA)

@rhatdan @imcleod @jwhonce PTAL

**Comment by rhatdan** [comment]
I am going to merge, my review was from a while ago, but I never completed it.  Perhaps as we go foward we could separate out this patch into its own file.

**Comment by runcom** [comment]
Dan, distribution code is pretty simple so this is not adding any burden to my rebases

**Comment by rhatdan** [comment]
Ok

**Pull request merged**
