### PR TITLE
Avoid unnecessary blob uploads

### PR DESCRIPTION
**Pull request by miminar**
This is a minimal patch fixing https://bugzilla.redhat.com/show_bug.cgi?id=1372065

Whole patch has been submitted upstream as https://github.com/docker/docker/pull/26564

### CODE REVIEW

**Comment by rhatdan** [comment]
@runcom @mrunalp PTAL  

I would like to see some reaction from upstream before making the change.

**Comment by runcom** [comment]
This patch looks good to me but I would also want to see some reaction from upstream so unless we're in a rush to carry this I would wait.

**Comment by runcom** [comment]
@miminar we will need another patch for docker-1.12 as well (or backport the one which will hopefully merged upstream) - just a reminder.

**Comment by mrunalp** [comment]
Yeah agree.

**Comment by miminar** [comment]
Got LGTM upstream, I'll rebase for 1.10 once merged. The upstream fix differs a lot from this.

**Comment by runcom** [comment]
> Got LGTM upstream, I'll rebase for 1.10 once merged. The upstream fix differs a lot from this.

@miminar we'll need another path for docker-1.12 branch as well - upstream can be easily applied to docker-1.13 instead.

**Comment by miminar** [comment]
Obsoleted by #202. Closing.

**Pull request closed without merging**
