### PR TITLE
Pull by digest rhel7 1.10.3

### PR DESCRIPTION
**Pull request by runcom**
Same as https://github.com/projectatomic/docker/pull/192 but fixed from BZ#1380474

@ncdc @rhatdan @derekwaynecarr PTAL - this includes the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1380474 also.

### CODE REVIEW

**Comment by ncdc** [comment]
I reviewed the 1 new commit. LGTM

**Comment by runcom** [comment]
@rhatdan @derekwaynecarr should we merge this one?

**Comment by rhatdan** [comment]
We can merge and then hopefully never ship.

**Comment by runcom** [comment]
This patch series is also needed for signatures, so better merge this in my opinion at this point (since we'll ship signatures verification as well)

**Comment by rhatdan** [comment]
@derekwaynecarr We plan on shippint docker-1.12 as default in rhel7.3.1 if OpenShift can handle it.  We do not plan on ever shipping docker-1.10 again, unless we have to.

**Comment by rhatdan** [comment]
Merging do to requirement by OpenShift, but it has not been decided whether we ship or not.

**Comment by brenton** [comment]
@ncdc, @derekwaynecarr can you tell us exactly what is broken in OCP with out this?  It's not clear to me if lacking this fix will mean 3.3.1 is catastrophically broken or if something that was already broken will simply continue not to work.

**Comment by derekwaynecarr** [comment]
@brenton - OCP 3.3.1 is not horribly broken without this change, but third-parties are unable to audit the cluster to know the exact image that is being run by a pod on a node.

User scenario:

1. `oc run nginx --image=nginx`
2. `oc get pod nginx -o yaml`

With the change:

The `pod.status.containerStatuses[0].ImageID` field will have a value with form:

`docker-pullable://docker.io/nginx@sha256:e40499ca855c9edfb212e1c3ee1a6ba8b2d873a294d897b4840d49f94d20487c`.

The reported ImageID in this case represents a value that a third-party can docker pull to know the EXACT image that was being run on the node to support scanning.

Without this change:

The `pod.status.containerStatuses[0].ImageID` field will have a value with form:

`docker://sha256:a5311a310510e5eaff3cfbb22b65d9ce11ddc15e266833909551334d48491921`

This ImageID is not pullable by third-party systems to know the actual image that was running on the node.

**Pull request merged**
