### PR TITLE
Prevent unnecessary blob uploads (rhel7-1.10.3)

### PR DESCRIPTION
**Pull request by miminar**
Backporting upstream docker/docker#26564

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1372065

Obsoletes #196

### CODE REVIEW

**Comment by runcom** [comment]
LGTM, @rhatdan want to merge?

**Comment by runcom** [comment]
We need to backport this to fedora as well but I'm taking care of it (thx)

**Comment by rhatdan** [comment]
I guess so, although there is a chance that we will not ship a new docker-1.10, could be moving to docker-1.12 for RHEL 7.3.1

**Comment by runcom** [comment]
@rhatdan alright, let's keep this open and merge only when we're sure about what we do in rhel for 7.3.x

**Pull request closed without merging**
