### PR TITLE
Shared rootfs Test Patches

### PR DESCRIPTION
**Pull request by rhvgoyal**
Hi,

I want to these patches to be merged into a test branch so that these can be built for testing.

Vivek

### CODE REVIEW

**Comment by rhvgoyal** [comment]
cc @rhatdan @runcom @lsm5, @jeremyeder

**Comment by runcom** [comment]
Fine

**Comment by rhatdan** [comment]
So lets create a v1.12-read-only branch of docker with all of these patches plus our docker-1.12 patches.

**Comment by jeremyeder** [comment]
Please link to a set of RPMs when they're available.  Note that I'm out of pocket until next Monday.

**Comment by rhvgoyal** [comment]
These are very hacky patches right now. Uploading early to get some early test results. To launch a read-only shared rootfs container try this.

./docker run -ti --read-only --shared-rootfs --tmpfs /run --tmpfs /tmp fedora bash

These patches don't work with selinux yet. So remember to disable selinux in docker while testing.

**Comment by rhatdan** [comment]
Is this still open or should we close this?

**Comment by jeremyeder** [comment]
The upstream work hasn't been completed (perhaps never will?)  I guess this PR is just to hold the test patches.

**Comment by rhvgoyal** [comment]
Lets close this for now. Nobody is working on this upstream yet.

**Pull request closed without merging**
