### PR TITLE
BACKPORT: Do not use stream encoders

### PR DESCRIPTION
**Pull request by mrunalp**
Don't use json Encoder as it adds a new line causing sync issues between parent and child process in container setup.

### CODE REVIEW

**Comment by runcom** [comment]
Mrunal what was the BZ for this fix just curious 

LGTM are we going to ship this in rhel now that docker and docker-latest both point to 1.10.3

**Comment by mrunalp** [comment]
@runcom Openshift is running into the sync peer issue for summit demo and they don't want to switch to 1.10 for demo given the other issues they have with 1.10

**Comment by mrunalp** [comment]
@runcom It still needs a BZ.

**Comment by mrunalp** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1344125

**Comment by runcom** [comment]
ack

**Comment by runcom** [comment]
@mrunalp asked because I remembered there were these two bugs which your fix here is also resolving:

https://bugzilla.redhat.com/show_bug.cgi?id=1339164
https://bugzilla.redhat.com/show_bug.cgi?id=1333094

**Comment by mrunalp** [comment]
@runcom Nice! Not sure whether we are going to cut a new release but hopefully should unblock OpenShift demo. 
@rhatdan ping

**Pull request merged**
